server:
  port: 8080
  address: backend

spring:
  main:
    banner_mode: 'off'
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto: create
  datasource:
    driver-class: "org.postgresql.Driver"
    url: "jdbc:postgresql://db:5432/postgres"
    username: "postgres"
    password: "postgres"



